global:
  scrape_interval: 5s  # Frequência de coleta de métricas

scrape_configs:
  - job_name: 'fluxo-caixa-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5116']  
